-- MySQL Script generated by MySQL Workbench
-- sex 12 mar 2021 15:54:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema contratos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema contratos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `contratos` ;
USE `contratos` ;

-- -----------------------------------------------------
-- Table `contratos`.`contratante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contratos`.`contratante` (
  `idcontratante` INT NOT NULL,
  `razao_social` VARCHAR(90) NULL,
  `endereco` VARCHAR(200) NULL,
  `cnpj` BIGINT(14) NULL,
  `telefone` VARCHAR(10) NULL,
  PRIMARY KEY (`idcontratante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contratos`.`contratado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contratos`.`contratado` (
  `idcontratado` INT NOT NULL,
  `razao_social` VARCHAR(90) NULL,
  `endereco` VARCHAR(200) NULL,
  `cnpj` BIGINT(14) NULL,
  `telefone` VARCHAR(10) NULL,
  PRIMARY KEY (`idcontratado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contratos`.`tipo_contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contratos`.`tipo_contrato` (
  `idtipo_contrato` INT NOT NULL,
  `tipo` VARCHAR(20) NULL,
  `objeto` VARCHAR(1000) NULL,
  PRIMARY KEY (`idtipo_contrato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contratos`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contratos`.`contrato` (
  `idcontrato` INT NOT NULL,
  `tipo` INT NULL,
  `contratante` INT NULL,
  `contratado` INT NULL,
  `vigencia` DATE NULL,
  `carencia` INT NULL,
  `prazo` DATE NULL,
  `valores` FLOAT NULL,
  `status` VARCHAR(20) NULL,
  `datadecriacao` DATE NULL,
  PRIMARY KEY (`idcontrato`),
  INDEX `idtipo_contrato_idx` (`tipo` ASC) VISIBLE,
  INDEX `idcontratante_idx` (`contratante` ASC) VISIBLE,
  INDEX `idcontratado_idx` (`contratado` ASC) VISIBLE,
  CONSTRAINT `idtipo_contrato`
    FOREIGN KEY (`tipo`)
    REFERENCES `contratos`.`tipo_contrato` (`idtipo_contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idcontratante`
    FOREIGN KEY (`contratante`)
    REFERENCES `contratos`.`contratante` (`idcontratante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idcontratado`
    FOREIGN KEY (`contratado`)
    REFERENCES `contratos`.`contratado` (`idcontratado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
